version: '3.7'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: hackmate-server
    container_name: hackmate-server
    command: npm start
    volumes:
      - ./server/:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    env_file: ./server/.env
    environment:
      - NODE_ENV=development
    networks:
      - app-network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: hackmate-client
    container_name: hackmate-client
    command: npm run dev
    volumes:
      - ./client/:/usr/app
      - /usr/app/node_modules
    depends_on:
      - server
    ports:
      - "5173:5173"
    networks:
      - app-network

networks:
    app-network:
        driver: bridge

volumes:
    node_modules:
    web-root:
      driver: local


